### ISSUE TITLE
I have a question about a old project

### ISSUE THREAD

**Issue by Cool-pig-9** [sereneblue/imgr3ds#2]
hello i know this is in the very wrong place but i had a question about one of your other projects and didn't know where else to ask. sorry for the in convince.

so i was looking at 3ds email client and i found:
https://devpost.com/software/3dsmail
witch i believe you made because i found a link to this github from this link:
https://devpost.com/software/surftv#updates 

anyway i have a cupple questions
do you still have it? (unlikely after 8 years but still)
and if you do does it work?
also (even if it doesnt work) is there a way i could get the source code.

anyway, the project looked cool and i couldn't find it anywhere. 
thanks in advance and once again sorry for posting it here (i couldnt find your email)

**Comment by sereneblue** [comment]
Hi,

During the event, I actually lost the source code from a corrupted SD card so I only had some UI screenshots. It was only able to send emails if I hardcoded the data but it wasn't really functional.

**Comment by Cool-pig-9** [comment]
Thanks for your response! corrupted Data truly sucks. 

Anyway thanks anywho
